# What is numpy?
### NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

### At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# Numpy Arrays Vs Python Sequences
### NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

### The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

### NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

### A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating Numpy arrays

In [70]:
# np .array
import numpy as np
a=np.array([1,2,3,4,5])  # it requires a list
print(a)

[1 2 3 4 5]


In [71]:
# 2d and 3d
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [72]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [73]:
# dtype
d=np.array([1,2,3,4,5],dtype='float') # creating array of other data types as well
print(d)

[1. 2. 3. 4. 5.]


In [74]:
# np.arange
e=np.arange(1,10)
print(e)

[1 2 3 4 5 6 7 8 9]


In [75]:
f=np.arange(1,10,2)
print(f)

[1 3 5 7 9]


In [76]:
# np.reshape
g=np.arange(1,26).reshape(5,5)
print(g)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [77]:
# np.ones and np.zeros
h=np.ones((3,3))
print(h)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [78]:
i=np.zeros((3,4))
print(i)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [79]:
# np.random
j=np.random.rand(3,3)
print(j)

[[0.0845869  0.79731838 0.09092442]
 [0.57642173 0.15751147 0.99896972]
 [0.69953585 0.40721284 0.79673073]]


In [80]:
k=np.random.random((3,3))
print(k)

[[0.56031169 0.8872908  0.30031544]
 [0.69335252 0.15059034 0.95216307]
 [0.46016768 0.43542232 0.53046227]]


In [81]:
# np.linspace
l=np.linspace(1,10,20)  # 20 numbers between 1 and 10
print(l)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [82]:
# np.identity
m=np.identity(5)
print(m)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Array Attributes

### SInce numpy arrays are objects of numpy class it can access methods of numpy class

In [83]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [84]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [86]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [87]:
# ndim
a1.ndim

1

In [88]:
a2.ndim

2

In [89]:
a3.ndim

3

In [90]:
#shape
a1.shape

(10,)

In [91]:
a2.shape

(3, 4)

In [92]:
a3.shape  # it means that there are 2 2d arrays of size 2*2

(2, 2, 2)

In [93]:
# size
a1.size

10

In [94]:
a2.size

12

In [95]:
a3.size

8

In [96]:
# itemsize
a1.itemsize

4

In [97]:
a2.itemsize

8

In [98]:
a3.itemsize

4

In [99]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [100]:
# Changing Data Types
print(a3.dtype)


int32


In [101]:
a3=a3.astype('float')
print(a3.dtype)

float64


In [102]:
a3=a3.astype('int64')
print(a3.dtype)

int64


# Array Operations

In [103]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [104]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### scaler operations

In [106]:

a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [107]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### vector operations

In [108]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [109]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Functions

In [110]:
a1=np.random.rand(3,3)
a1=np.round(a1*100)
print(a1)

[[83.  2.  2.]
 [47. 52. 31.]
 [46. 95. 58.]]


In [111]:
# max,min,sum,prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

95.0
2.0
416.0
6375443622080.0


In [112]:
# 0---> column and 1----> row
np.max(a1,axis=1)

array([83., 52., 95.])

In [113]:
# mean,median,std,var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))



46.22222222222222
47.0
29.902722944678015
894.172839506173


In [114]:
print(np.mean(a1,axis=0))

[58.66666667 49.66666667 30.33333333]


In [115]:
# trigonometric functions
print(np.sin(a1))


[[ 0.96836446  0.90929743  0.90929743]
 [ 0.12357312  0.98662759 -0.40403765]
 [ 0.90178835  0.68326171  0.99287265]]


In [116]:
# dot product
a2=np.arange(1,10).reshape(3,3)
a3=np.arange(11,20).reshape(3,3)

print(a2)
print(a3)

ans=np.dot(a2,a3)
print(ans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [117]:
# log and exp
print(np.log(a1))

[[4.41884061 0.69314718 0.69314718]
 [3.8501476  3.95124372 3.4339872 ]
 [3.8286414  4.55387689 4.06044301]]


In [118]:
print(np.exp(a1))

[[1.11286375e+36 7.38905610e+00 7.38905610e+00]
 [2.58131289e+20 3.83100800e+22 2.90488497e+13]
 [9.49611942e+19 1.81123908e+41 1.54553894e+25]]


In [119]:
# round, floor, ceil
print(np.round(a1))
print(np.floor(a1))
print(np.ceil(a1))


[[83.  2.  2.]
 [47. 52. 31.]
 [46. 95. 58.]]
[[83.  2.  2.]
 [47. 52. 31.]
 [46. 95. 58.]]
[[83.  2.  2.]
 [47. 52. 31.]
 [46. 95. 58.]]


# Indexing and slicing

In [120]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [121]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [122]:
a1[-1]

9

In [123]:
a1[0]   # 1d array behaves as same as we did in python lists in casde of 1d array

0

In [124]:
a2[1][2]

6

In [125]:
a2[2][3]

11

In [126]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [127]:
print(a3[1][1][0])

6


In [128]:
print(a3[1,0,1])

5


In [129]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
print(a1[2:5])  # slicing in array is same as in python

[2 3 4]


In [131]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
print(a2[0,:])  # all elements of 0th row

[0 1 2 3]


In [133]:
print(a2[:,0])  # all elements of 0th column

[0 4 8]


In [134]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
print(a2[::2,::3])

[[ 0  3]
 [ 8 11]]


In [136]:
print(a2[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [137]:
print(a2[1,::3])

[4 7]


In [138]:
print(a2[0:2,1:4])

[[1 2 3]
 [5 6 7]]


In [139]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [140]:
a3=np.arange(27).reshape(3,3,3)

In [141]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [142]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [143]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [144]:
a3[0,1,:]

array([3, 4, 5])

In [145]:
a3[1,:,1]

array([10, 13, 16])

In [146]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [148]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating


In [149]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [152]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [153]:
for i in a2:
    
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [154]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [155]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [156]:
# Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [158]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [159]:
# Ravel

a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [160]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Ravel function is used to convert any dimensional array to 1d array

# Stacking

In [164]:
# Horizontal Stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a6=np.hstack((a4,a5))
print(a6)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [165]:
# Vertical Stacking
a7=np.vstack((a4,a5))

In [166]:
print(a7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Stacking is used to join the data (eg -> when data comes from multiple sources and we have to club it together) ..The only requirement in stacking is that it shape must be same.

# Splitting

### It is just the reverse operation of stacking

In [167]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [169]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]