In [1]:
import numpy as np

# np.sort
### It returns a sorted copy of an array.


In [2]:
# code
a=np.random.randint(1,100,15)
a

array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[ 5, 81, 46, 31],
       [47, 46,  5, 81],
       [29, 31, 83, 39],
       [59, 63, 82, 42],
       [46, 49, 76, 59],
       [15, 56, 81, 69]])

In [4]:
np.sort(a)

array([13, 23, 25, 25, 28, 45, 48, 49, 53, 62, 66, 67, 76, 77, 94])

In [5]:
np.sort(b)

array([[ 5, 31, 46, 81],
       [ 5, 46, 47, 81],
       [29, 31, 39, 83],
       [42, 59, 63, 82],
       [46, 49, 59, 76],
       [15, 56, 69, 81]])

In [6]:
np.sort(b,axis=0)

array([[ 5, 31,  5, 31],
       [15, 46, 46, 39],
       [29, 49, 76, 42],
       [46, 56, 81, 59],
       [47, 63, 82, 69],
       [59, 81, 83, 81]])

In [7]:
np.sort(b,axis=0)[::-1] # in descending order

array([[59, 81, 83, 81],
       [47, 63, 82, 69],
       [46, 56, 81, 59],
       [29, 49, 76, 42],
       [15, 46, 46, 39],
       [ 5, 31,  5, 31]])

# np.append()
### The np.append() appends values along the mentioned axis at the end of the array.

In [8]:
# code
a

array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [9]:
np.append(a,500)

array([ 48,  66,  67,  49,  28,  25,  62,  13,  25,  53,  77,  45,  23,
        76,  94, 500])

In [10]:
b.shape

(6, 4)

In [11]:

np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 5., 81., 46., 31.,  1.],
       [47., 46.,  5., 81.,  1.],
       [29., 31., 83., 39.,  1.],
       [59., 63., 82., 42.,  1.],
       [46., 49., 76., 59.,  1.],
       [15., 56., 81., 69.,  1.]])

# np.concatenate
### np.concatenate() function concatenates a sequence of arrays along an existing axis.

In [12]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
### with the help of np.unique() method, we can get unique values from an array given as parameter in np.unique() method.

In [15]:
# code
e=np.array([1,1,3,2,2,2,3,4,3,3,5,4,4,6,4,7,5,8])
e

array([1, 1, 3, 2, 2, 2, 3, 4, 3, 3, 5, 4, 4, 6, 4, 7, 5, 8])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8])

# np.expand_dims
### With the help of np.expand_dims() method, we can get the expanded dimension of an array.

In [17]:
# code
a


array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [18]:
np.expand_dims(a,axis=0)

array([[48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94]])

In [19]:
np.expand_dims(a,axis=1)

array([[48],
       [66],
       [67],
       [49],
       [28],
       [25],
       [62],
       [13],
       [25],
       [53],
       [77],
       [45],
       [23],
       [76],
       [94]])

# np.where
### The np.where() function returns the indices of elements in input array where the given condition is satisfied.

In [20]:
a

array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [21]:
# find the indices of all the values which have value greater than 50
np.where(a>50)

(array([ 1,  2,  6,  9, 10, 13, 14], dtype=int64),)

In [22]:
# replace all the values above 50 with 0
np.where(a>50,0,a)   # np.where(condition,true,false)

array([48,  0,  0, 49, 28, 25,  0, 13, 25,  0,  0, 45, 23,  0,  0])

# np.argmax
### The np.argmax() function returns indices of the maximum element of the array in a particular axis.

In [23]:
# code
a


array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [24]:
np.argmax(a)

14

In [25]:
b

array([[ 5, 81, 46, 31],
       [47, 46,  5, 81],
       [29, 31, 83, 39],
       [59, 63, 82, 42],
       [46, 49, 76, 59],
       [15, 56, 81, 69]])

In [26]:
np.argmax(b)

10

In [27]:
np.argmax(b,axis=1)

array([1, 3, 2, 2, 2, 2], dtype=int64)

In [28]:
np.argmin(a)

7

# np.cumsum
### np.cumsum() function is used when we want to compute the commulative sum of array elements over a given axis.

In [29]:
np.cumsum(a)

array([ 48, 114, 181, 230, 258, 283, 345, 358, 383, 436, 513, 558, 581,
       657, 751])

In [30]:
np.cumsum(b)

array([   5,   86,  132,  163,  210,  256,  261,  342,  371,  402,  485,
        524,  583,  646,  728,  770,  816,  865,  941, 1000, 1015, 1071,
       1152, 1221])

In [31]:
# np.cumprod
np.cumprod(a)

array([         48,        3168,      212256,    10400544,   291215232,
       -1309553792,   412043520,  1061598464,   770157824, -2131308288,
        -901980928, -1934436096, -1542357248, -1255033856, -2009065472])

In [32]:
np.cumprod(b)

array([          5,         405,       18630,      577530,    27143910,
        1248619860,  1948132004, -1115097628,  2021907156, -1745387604,
        1161716932, -1937679908,  1641002420,   303937356,  -846940584,
       -1211766160,    93331488,   278275616,  -325889664, -2047620992,
        -649543808, -2014714880,    16851968,  1162785792])

# np.percentile
### np.percentile() function is used to compute the nth percentile of the given data(array elements) along the specified axis.

In [33]:
a

array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [34]:
np.percentile(a,100)

94.0

In [35]:
np.percentile(a,0)

13.0

In [36]:
np.percentile(a,50)

49.0

In [37]:
np.percentile(a,75)

66.5

# np.histogram
### numy has a built in np.histogram() function which represents the frequency of data distribution in the graphical form.

In [38]:
a

array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [39]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 4, 0, 3, 1, 3, 2, 0, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef
### returns Pearson product-moment correlation coefficients.

In [40]:
salary=np.array([20000,40000,25000,35000,60000])
experience=[1,3,4,2,2]

In [41]:
np.corrcoef(salary,experience)  # it has 4 values  --> salary-salary  --->salary-experience  --> experience-salary   --> experience-experience

array([[ 1.        , -0.02816064],
       [-0.02816064,  1.        ]])

# np.i sin
### np.isin() method, we can see that one array having values are checkedin a different numpy array having different numoyb array having different elements with different sizes.


#### ek sath multiple items ko search krme ke kam hota hoga

In [42]:
a

array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [46]:
items=[10,20,30,40,50,60,70,80,90,100]

In [47]:
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [48]:
np.isin

<function numpy.isin(element, test_elements, assume_unique=False, invert=False, *, kind=None)>

# np.flip
### np.flip() function reverses the order of array elements along the specified axis, preserving tha shape of the array.

In [49]:
a

array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [50]:
np.flip(a)

array([94, 76, 23, 45, 77, 53, 25, 13, 62, 25, 28, 49, 67, 66, 48])

In [51]:
b

array([[ 5, 81, 46, 31],
       [47, 46,  5, 81],
       [29, 31, 83, 39],
       [59, 63, 82, 42],
       [46, 49, 76, 59],
       [15, 56, 81, 69]])

In [52]:
np.flip(b)

array([[69, 81, 56, 15],
       [59, 76, 49, 46],
       [42, 82, 63, 59],
       [39, 83, 31, 29],
       [81,  5, 46, 47],
       [31, 46, 81,  5]])

In [53]:
np.flip(b,axis=0)

array([[15, 56, 81, 69],
       [46, 49, 76, 59],
       [59, 63, 82, 42],
       [29, 31, 83, 39],
       [47, 46,  5, 81],
       [ 5, 81, 46, 31]])

In [54]:
np.flip(b,axis=1)

array([[31, 46, 81,  5],
       [81,  5, 46, 47],
       [39, 83, 31, 29],
       [42, 82, 63, 59],
       [59, 76, 49, 46],
       [69, 81, 56, 15]])

# np.put()
### The np.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. It does the permanent changes.

In [55]:
a

array([48, 66, 67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

In [56]:
np.put(a,[0,1],[110,220])

In [57]:
a

array([110, 220,  67,  49,  28,  25,  62,  13,  25,  53,  77,  45,  23,
        76,  94])

# np.delete
### np.delete() function returns a new array with the deletion of sub-arrays along with their indices.

In [59]:
a

array([110, 220,  67,  49,  28,  25,  62,  13,  25,  53,  77,  45,  23,
        76,  94])

In [60]:
np.delete(a,[0,1])

array([67, 49, 28, 25, 62, 13, 25, 53, 77, 45, 23, 76, 94])

# Set Functions
### np.unionid
### np.intersect1d
### np.setdiff1d
### np.setxor1d
### np.in1d


In [66]:
m=np.array([1,2,3,4,5])
n=np.array([6,7,8,9,10])

print(np.union1d(m,n))
print(np.intersect1d(m,n))
print(np.setdiff1d(m,n))
print(np.setdiff1d(n,m))
print(np.setxor1d(m,n))
print(np.setxor1d(n,m))  ### symmetric difference..means common wale ko hata dega baki print kar dega
print(np.in1d(m,n))
print(np.in1d(m,1))  ### it is like a membership operator



[ 1  2  3  4  5  6  7  8  9 10]
[]
[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False]
[ True False False False False]


# np.clip()
### np.clip() function is used to clip(limit) the values in the array.

In [67]:
a

array([110, 220,  67,  49,  28,  25,  62,  13,  25,  53,  77,  45,  23,
        76,  94])

In [68]:
np.clip(a,25,75)

array([75, 75, 67, 49, 28, 25, 62, 25, 25, 53, 75, 45, 25, 75, 75])